#!/usr/bin/env python3.6

from __future__ import absolute_import
import logging
import os
import sys

import pyglet

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'src'))
from deathbeam.game import Game


if __name__ == '__main__':
    logging.basicConfig(format=('%(asctime)-15s\t%(levelname)s\t'
                                '%(message)s (%(filename)s:%(lineno)d)'),
                        level=logging.DEBUG)
    Game()
    pyglet.app.run()
