#!/usr/bin/env python2.7

from __future__ import absolute_import
import os
import sys

import pyglet

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'src'))
from deathbeam.game import Game


if __name__ == '__main__':
    Game()
    pyglet.app.run()
